#!/bin/sh
# Print the Homebrew formula for a tracebridge release.
#
#   packaging/homebrew/formula.sh <version> <dist dir> [owner/repo] > tracebridge.rb
#
# <dist dir> holds the release archives' .sha256 files
# (tracebridge-<target>.tar.gz.sha256) and, when present, the bottles' .sha256
# files from bottles.sh; those add a bottle block, so Homebrew pours the
# bottle instead of "building" (which requires the Command Line Tools). The Update formulae workflow of
# haoyibits/homebrew-tap downloads this script from the release tag, runs it
# and commits the result.
set -eu

version="${1:?version, e.g. 0.1.0}"
dist="${2:?directory with the .sha256 files}"
repo="${3:-haoyibits/tracebridge}"
base="https://github.com/$repo/releases/download/v$version"

bottle_block() {
    lines=""
    for tag in arm64_sonoma sonoma arm64_linux x86_64_linux; do
        file="$dist/tracebridge-$version.$tag.bottle.tar.gz.sha256"
        [ -f "$file" ] || continue
        lines="$lines    sha256 cellar: :any_skip_relocation, $tag: \"$(cut -d ' ' -f 1 "$file")\"
"
    done
    [ -n "$lines" ] || return 0
    printf '\n  bottle do\n    root_url "%s"\n%s  end\n' "$base" "$lines"
}

sha() {
    file="$dist/tracebridge-$1.tar.gz.sha256"
    [ -f "$file" ] || { echo "formula.sh: missing $file" >&2; exit 1; }
    cut -d ' ' -f 1 "$file"
}

cat <<FORMULA
# Generated by packaging/homebrew/formula.sh for tracebridge $version; do not edit.
class Tracebridge < Formula
  desc "Drive Lauterbach TRACE32 PowerView from the command line, VS Code and RustRover"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"
$(bottle_block)

  on_macos do
    on_arm do
      url "$base/tracebridge-aarch64-apple-darwin.tar.gz"
      sha256 "$(sha aarch64-apple-darwin)"
    end
    on_intel do
      url "$base/tracebridge-x86_64-apple-darwin.tar.gz"
      sha256 "$(sha x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "$base/tracebridge-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$(sha aarch64-unknown-linux-musl)"
    end
    on_intel do
      url "$base/tracebridge-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$(sha x86_64-unknown-linux-musl)"
    end
  end

  def install
    bin.install "tracebridge"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tracebridge --version")
  end
end
FORMULA
