#!/bin/sh
# Print the Homebrew formula for a tracebridge release.
#
#   packaging/homebrew/formula.sh <version> <dist dir> [owner/repo] > tracebridge.rb
#
# <dist dir> holds the release archives' .sha256 files
# (tracebridge-<target>.tar.gz.sha256). The release workflow runs this and
# commits the result to the tap repository <owner>/homebrew-tap.
set -eu

version="${1:?version, e.g. 0.1.0}"
dist="${2:?directory with the .sha256 files}"
repo="${3:-haoyibits/tracebridge}"
base="https://github.com/$repo/releases/download/v$version"

sha() {
    file="$dist/tracebridge-$1.tar.gz.sha256"
    [ -f "$file" ] || { echo "formula.sh: missing $file" >&2; exit 1; }
    cut -d ' ' -f 1 "$file"
}

cat <<FORMULA
# Generated by packaging/homebrew/formula.sh for tracebridge $version; do not edit.
class Tracebridge < Formula
  desc "Drive Lauterbach TRACE32 PowerView from the command line, VS Code and RustRover"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/tracebridge-aarch64-apple-darwin.tar.gz"
      sha256 "$(sha aarch64-apple-darwin)"
    end
    on_intel do
      url "$base/tracebridge-x86_64-apple-darwin.tar.gz"
      sha256 "$(sha x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "$base/tracebridge-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$(sha aarch64-unknown-linux-musl)"
    end
    on_intel do
      url "$base/tracebridge-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$(sha x86_64-unknown-linux-musl)"
    end
  end

  def install
    bin.install "tracebridge"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tracebridge --version")
  end
end
FORMULA
